#!/usr/bin/env bash
set -e
DATE=$(date +"%Y-%m-%d-%H%M")
echo "Creating snapshot from m0-mongodb"
gcloud compute disks snapshot m0-mongodb --snapshot-names m0-mongodb-$DATE
echo "Creating snapshot from m1-mongodb"
gcloud compute disks snapshot m1-mongodb --snapshot-names m1-mongodb-$DATE
set +e

