#!/usr/bin/env bash

_term() { 
  echo "Caught SIGTERM signal!" 
  kill -TERM "$child" 2>/dev/null
}

trap _term SIGTERM


SAGE_ROOT=/home/sage/sage-root
SAGE=$SAGE_ROOT/sage

# These two lines copied from ~/common:
export TEXINPUTS=.:$SAGE_ROOT/local/share/texmf:
# export GIT_DIR='/home/lmfdb/lmfdb.git/'
# GIT_DIR points to the bare git repository containing both beta and prod branches

export GIT_WORK_TREE='/home/lmfdb/lmfdb-git-prod'
cd $GIT_WORK_TREE
while true; do
    echo 'gunicorn -c gunicorn-config-prod lmfdb.website:app'
    $SAGE -sh -c 'cd $GIT_WORK_TREE; gunicorn -c gunicorn-config-prod lmfdb.website:app' &
    child=$!
    wait "$child"
    date
    sleep 10s;
done

