#!/usr/bin/env bash

killtree() {
    local _pid=$1
    local _sig=${2:--TERM}
    kill -stop ${_pid} # needed to stop quickly forking parent from producing children between child killing and parent killing
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

_term() { 
  echo "Caught SIGTERM signal!" 
  killtree $$ TERM
}

trap _term SIGTERM


SAGE_ROOT=/home/sage/sage-root
SAGE=$SAGE_ROOT/sage

# These two lines copied from ~/common:
export TEXINPUTS=.:$SAGE_ROOT/local/share/texmf:
# export GIT_DIR='/home/lmfdb/lmfdb.git/'
# GIT_DIR points to the bare git repository containing both beta and prod branches

export GIT_WORK_TREE='/home/lmfdb/lmfdb-git-prod'
cd $GIT_WORK_TREE
while true; do
    echo 'gunicorn -c gunicorn-config-prod lmfdb.website:app'
    $SAGE -sh -c 'cd $GIT_WORK_TREE; gunicorn -c gunicorn-config-prod lmfdb.website:app' 
    date
    sleep 10s;
done

