#!/usr/bin/env bash
echo 'Killing supervisord ...'
kill -TERM `cat /home/lmfdb/supervisord.pid`
echo 'Killing gunicorn ...'
for file in /home/lmfdb/gunicorn-*.pid; do
  name=${file#/home/lmfdb/gunicorn-}   # strip prefix
  echo branch = "${name%.pid}"   # strip suffix
  kill -TERM `cat $file`;
done
echo '... and done!'
